---
- name: Rollout ssh key to devices
  hosts: video_player
  tasks:
    - name: "Add to authorized keys"
      ansible.posix.authorized_key:
        user: "{{ ansible_facts['user_id'] }}"
        state: present
        key: "{{ lookup('file', key) }}"
