---
- name: Remove faulty apt source
  ansible.builtin.import_playbook: remove_apt_cdrom_source.yml

- name: Install Sudo
  ansible.builtin.import_playbook: install_sudo.yml

# - name: Full System upgrade (?)
#   ansible.builtin.import_playbook: upgrade_system.yml

- name: Add key to github account
  ansible.builtin.import_playbook: setup_ssh-key.yml

- name: Setup zsh/dotfiles
  ansible.builtin.import_playbook: install_dotfiles.yml

- name: Setup lingering user
  ansible.builtin.import_playbook: setup_lingering.yml

- name: Install seamless configs
  ansible.builtin.import_playbook: install_configs.yml

- name: Install audio drivers
  ansible.builtin.import_playbook: install_madi_driver.yml

- name: Install audio drivers
  ansible.builtin.import_playbook: install_dante_driver.yml


- name: Install jackd
  ansible.builtin.import_playbook: install_jack.yml

- name: Install audio-matrix
  ansible.builtin.import_playbook: install_audio-matrix.yml

- name: Install osc-kreuz
  ansible.builtin.import_playbook: install_osc-kreuz.yml

- name: Install IEM decoder
  ansible.builtin.import_playbook: install_iem_decoder.yml

- name: Install jack-connection-manager
  ansible.builtin.import_playbook: install_jack-connection-manager.yml

- name: Install wonder
  ansible.builtin.import_playbook: install_wonder.yml

- name: Enable Performance Mode
  ansible.builtin.import_playbook: setup_performance_mode.yml
- name: Setup grub
  ansible.builtin.import_playbook: setup_grub.yml

- name: Setup Logging
  ansible.builtin.import_playbook: setup_logging.yml
- name: Reboot
  ansible.builtin.import_playbook: reboot.yml

- name: Setup MADI settings
  ansible.builtin.import_playbook: setup_alsa_settings.yml
