---
- name: Setup HuFo Proxy Server
  hosts: all
  become_method: su
  vars:
    env_vars:
      - key: http_proxy
        value: http://10.30.70.155:8888
      - key: https_proxy
        value: http://10.30.70.155:8888
  vars_files:
    - ../vars/vault.yml
  tasks:
    - name: populate /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"

      with_items: "{{ env_vars }}"
      become: true

    - name: Keep proxy for sudo commands
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        line: 'Defaults env_keep = "http_proxy https_proxy"'
      become: true

    - name: Reset ssh connection to allow user changes to affect 'current login user'
      ansible.builtin.meta: reset_connection
