---
- name: Install configs
  hosts: all
  vars:
    repo_dir: /home/{{ ansible_user_id }}/configs
  vars_files:
    - ../vars/program_versions.yml
    - ../vars/vault.yml
  tasks:
    - name: Install Dependencies
      ansible.builtin.apt:
        name:
          - meson
        state: present
      become: true

    - name: Clone Repo
      ansible.builtin.git:
        repo: git@github.com:tu-studio/seamless-configs.git
        dest: "{{ repo_dir }}"
        version: "{{ config_version }}"
        update: true

    - name: Remove Meson Build dir
      ansible.builtin.file:
        state: absent
        path: "{{ repo_dir }}/build"

    - name: Meson Setup
      ansible.builtin.command:
        cmd: meson setup build --buildtype release -Dversioned_install=true -Dlocation={{ location }} -Dnode={{ inventory_hostname }}
        chdir: "{{ repo_dir }}"

    - name: Meson Install
      ansible.builtin.command:
        cmd: meson install -C build
        chdir: "{{ repo_dir }}"
      become: true

    - name: Systemd daemon reload
      ansible.builtin.systemd:
        daemon_reload: true
        scope: user
    - name: Systemd enable service
      ansible.builtin.systemd:
        service: jack.service
        enabled: true
        scope: user
        masked: false
