---
- name: Install Reaper systemd service
  hosts: player
  vars:
    systemd_service_name: reaper
  vars_files:
    - ../vars/program_versions.yml
    - ../vars/vault.yml
  tasks:

  # - name: Re-move desktop autostart file
  #   ansible.builtin.copy:
  #     src: "~/.config/autostart/cockos-reaper.desktop"
  #     dest: "~/cockos-reaper.desktop.old"
  #     remote_src: true

  - name: Remove desktop autostart file
    ansible.builtin.file:
      path: "~/.config/autostart/cockos-reaper.desktop"
      state: absent

  - name: Create systemd service file
    ansible.builtin.copy:
      dest: "/etc/systemd/user/{{ systemd_service_name }}.service"
      content: |
        [Unit]
        Description=REAPER
        After=network-online.target graphical-session.target jack.service dbus.service
        Wants=network-online.target graphical-session.target

        [Service]
        Type=simple
        ExecStart=/opt/REAPER/reaper
        Restart=on-failure

        [Install]
        WantedBy=default.target
      mode: u=rw,g=r,o=r
    become: true

  - name: Systemd daemon reload
    ansible.builtin.systemd:
      daemon_reload: true
      scope: user

  - name: Systemd enable service
    ansible.builtin.systemd:
      service: "{{ systemd_service_name }}.service"
      enabled: true
      scope: user
      masked: false

