---
- name: Install sudo
  hosts: all
  become_method: su
  become: yes
  vars_files:
    - ../vars/vault.yml
  tasks:
    - name: Install sudo
      apt:
        name: sudo
        update_cache: true
    - name: Add user to sudo group
      user:
        name: "{{ ansible_user }}"
        groups: sudo
        append: yes

    - name: reset ssh connection to allow user changes to affect 'current login user'
      meta: reset_connection
