---
- name: Install osc-kreuz
  hosts: all
  vars:
    repo_dir: /home/{{ ansible_user_id }}/osc-kreuz
    service_name: osc-kreuz
    ansible_become_pass: "{{ vault['ansible_become_pass'] }}"
  vars_files:
    - ../vars/vault.yml
  tasks:

    - name: Only install osc-kreuz on devices that are concerned
      ansible.builtin.meta: end_host
      when: not (services is defined) or (service_name not in services)

    - name: Install Dependencies
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-venv
          - meson
        state: present
      become: true

    - name: Clone Repo
      ansible.builtin.git:
        repo: git@github.com:tu-studio/osc-kreuz.git
        dest: "{{ repo_dir }}"
        single_branch: true
        version: main
        update: true

    - name: Remove Meson Build dir
      ansible.builtin.file:
        state: absent
        path: "{{ repo_dir }}/build"

    - name: Meson Setup
      ansible.builtin.command:
        cmd: meson setup -Dversioned_install=true build
        chdir: "{{ repo_dir }}"

    - name: Meson Install
      ansible.builtin.command:
        cmd: meson install -C build
        chdir: "{{ repo_dir }}"
      become: true

    - name: Systemd daemon reload
      ansible.builtin.systemd:
        daemon_reload: true
        scope: user
    - name: Systemd enable service
      ansible.builtin.systemd:
        service: osc-kreuz.service
        enabled: true
        scope: user
        masked: false
