---
- name: Install jack-connection-manager
  hosts: all
  vars:
    service_name: jack-connection-manager
    repo_dir: /home/{{ ansible_facts["user_id"] }}/jack-connection-manager
  vars_files:
    - ../vars/vault.yml
    - ../vars/program_versions.yml
  tasks:
    - name: Only install jack-connection-manager on devices that are concerned
      ansible.builtin.meta: end_host
      when: not (services is defined) or (service_name not in services)

    - name: Install Dependencies
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-venv
          - meson
        state: present
      become: true

    - name: Clone Repo
      ansible.builtin.git:
        repo: https://github.com/tu-studio/jack-connection-manager.git
        dest: "{{ repo_dir }}"
        version: "{{ jack_connection_manager_version }}"
        update: true

    - name: Remove Meson Build dir
      ansible.builtin.file:
        state: absent
        path: "{{ repo_dir }}/build"

    - name: Meson Setup
      ansible.builtin.command:
        cmd: meson setup -Dversioned_install=true build
        chdir: "{{ repo_dir }}"

    - name: Meson Install
      ansible.builtin.command:
        cmd: meson install -C build
        chdir: "{{ repo_dir }}"
      become: true

    - name: Systemd daemon reload
      ansible.builtin.systemd:
        daemon_reload: true
        scope: user
    - name: Systemd enable service
      ansible.builtin.systemd:
        service: jack-connection-manager.service
        enabled: true
        scope: user
        masked: false
