---
- name: Install audio-matrix
  hosts: all
  vars:
    service_name: audio-matrix
    repo_dir: /home/{{ ansible_user_id }}/audio-matrix
  vars_files:
    - ../vars/vault.yml
    - ../vars/program_versions.yml
  tasks:
    - name: Only install audio-matrix on devices that are concerned
      ansible.builtin.meta: end_host
      when: not (services is defined) or (service_name not in services)

    - name: Install Dependencies
      ansible.builtin.apt:
        name:
          - cmake
          - build-essential
          - libjack-jackd2-dev
          - liblo-dev
        state: present
      become: true

    - name: Clone Repo
      ansible.builtin.git:
        repo: https://github.com/tu-studio/audio-matrix.git
        dest: "{{ repo_dir }}"
        version: "{{ audio_matrix_version }}"
        update: true

    - name: Cmake configure build
      ansible.builtin.command:
        cmd: cmake -B build -DCMAKE_BUILD_TYPE=Release -DVERSIONED_INSTALL=ON
        chdir: "{{ repo_dir }}"

    - name: Cmake build
      ansible.builtin.command:
        cmd: cmake --build build --config Release
        chdir: "{{ repo_dir }}"

    - name: Cmake install
      ansible.builtin.command:
        cmd: cmake --build build --config Release --target install
        chdir: "{{ repo_dir }}"
      become: true

    - name: Systemd daemon reload
      ansible.builtin.systemd:
        daemon_reload: true
        scope: user

    - name: Systemd enable service
      ansible.builtin.systemd:
        service: audio-matrix.service
        enabled: true
        state: restarted
        scope: user
        masked: false
