---
- name: remove cdrom apt repo
  hosts: all
  become: true
  become_method: su
  vars_files:
    - ../vars/vault.yml
  tasks:
    - name: Remove specified repository from sources list
      ansible.builtin.apt_repository:
        repo: deb cdrom:[Debian GNU/Linux 12.7.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20240831-10:40]/ bookworm contrib main non-free-firmware
        state: absent
