---
- name: Setup Grub
  hosts: all
  become: true
  vars_files:
    - ../vars/vault.yml
  tasks:
    - name: Change Grub CMDLine linux default
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_pstate=disable cpufreq.default_governor=performance"
      register: changed_grub
    - name: Update Grub
      ansible.builtin.command:
        cmd: update-grub
      when: changed_grub.changed
    - name: Reboot
      ansible.builtin.reboot:
      when: changed_grub.changed
        
