---
- name: Setup SSH key
  hosts: all
  vars_files:
    - ../vars/vault.yml
  tasks:
    - name: Generate SSH key
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_rsa
    - name: Read SSH public key to authorize
      ansible.builtin.shell: cat ~/.ssh/id_rsa.pub
      register: ssh_pub_key
    - name: Authorize key with GitHub
      delegate_to: localhost
      community.general.github_key:
        name: "{{ inventory_hostname }}"
        token: "{{ github_token }}"
        pubkey: '{{ ssh_pub_key.stdout }}'
