---
- name: Setup Player PC
  hosts: player
  vars:
    home_dir: /home/{{ ansible_user_id }}/
    dir: /home/{{ ansible_user_id }}/reaper
    archive_name: reaper716_linux_x86_64.tar.xz
    url: https://www.reaper.fm/files/7.x/reaper716_linux_x86_64.tar.xz

  vars_files:
    - ../vars/vault.yml
  tasks:
  # setup GPU
    - name: Add Repos
      ansible.builtin.command:
        cmd: apt-add-repository -yn contrib non-free non-free-firmware
      become: true
      register: apt_repos
      changed_when: "'Added' in apt_repos.stdout"

    - name: Update Apt Cache
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: apt_repos.changed 
      
    - name: Install Nvidia drivers
      ansible.builtin.apt:
        name:
          - nvidia-driver
          - firmware-misc-nonfree
      become: true

    - name: Enable modesetting driver
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/nvidia_drm.conf
        line: options nvidia_drm modeset=1
      become: true
      register: driver_enabled

    - name: Update initramfs
      ansible.builtin.command:
        cmd: update-initramfs -u
      become: true
      when: driver_enabled.changed

    - name: Reboot
      ansible.builtin.reboot:
      when: driver_enabled.changed

    # disable systemd services
    - name: Disable pulseaudio
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        masked: true
        state: stopped
        scope: user
      become: false
      loop: [pulseaudio.service, pulseaudio.socket]

    - name: Disable sleep, suspend, hibernate and hybrid sleep and such
      ansible.builtin.systemd:
        name: "{{ item }}"
        masked: true
        enabled: false
        state: stopped
      become: true
      loop: [sleep.target, suspend.target, hibernate.target, hybrid-sleep.target]

    # Setup service for alsa_in for the danteinterface
    - name: Systemd daemon reload
      ansible.builtin.systemd:
        daemon_reload: true
        scope: user

    - name: Install jack_dante service
      ansible.builtin.systemd:
        service: jack_dante.service
        enabled: true
        state: restarted
        scope: user
        masked: false

    # install REAPER
    - name: Download REAPER
      ansible.builtin.get_url:
        url: "{{ url }}"
        dest: "{{ home_dir }}"
      register: reaper_download

    - name: Extract reaper archive
      ansible.builtin.unarchive:
        remote_src: true
        src: "{{ home_dir }}/{{ archive_name }}"
        dest: "{{ home_dir }}"
      when: reaper_download.changed

    - name: Install REAPER
      ansible.builtin.command:
        cmd: ./install-reaper.sh --install /opt --usr-local-bin-symlink --integrate-desktop
        chdir: "{{ home_dir }}/reaper_linux_x86_64"
      become: true
      when: reaper_download.changed

    # - name: Setup

