---
- name: Setup Player PC
  hosts: player
  vars:
    sws_archive: ~/Downloads/sws-2.14.0.3-Linux-x86_64.tar.xz
    # reaper archive name and url are specified in program_versions.yml
    home_dir: /home/{{ ansible_user_id }}/
    dir: /home/{{ ansible_user_id }}/reaper
    reaper_config_dir: "{{ home_dir }}/.config/REAPER"

    systemd_service_name: reaper

  vars_files:
    - ../vars/vault.yml
    - ../vars/program_versions.yml
    - ../vars/vault.yml
  tasks:
    # disable systemd services
    - name: Disable pulseaudio
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        masked: true
        state: stopped
        scope: user
      become: false
      loop: [pulseaudio.service, pulseaudio.socket]

    - name: Disable sleep, suspend, hibernate and hybrid sleep and such
      ansible.builtin.systemd:
        name: "{{ item }}"
        masked: true
        enabled: false
        state: stopped
      become: true
      loop:
        [sleep.target, suspend.target, hibernate.target, hybrid-sleep.target]

    # install REAPER
    - name: Download REAPER
      ansible.builtin.get_url:
        url: "{{ reaper_url }}"
        dest: "{{ home_dir }}"
      register: reaper_download

    - name: Extract reaper archive
      ansible.builtin.unarchive:
        remote_src: true
        src: "{{ home_dir }}/{{ reaper_archive_name }}"
        dest: "{{ home_dir }}"
      when: reaper_download.changed

    - name: Install REAPER
      ansible.builtin.command:
        cmd: ./install-reaper.sh --install /opt --usr-local-bin-symlink --integrate-desktop
        chdir: "{{ home_dir }}/reaper_linux_x86_64"
      become: true
      when: reaper_download.changed

    - name: install sws extensions (from local folder)
      ansible.builtin.unarchive:
        src: "{{ sws_archive }}"
        dest: "{{ reaper_config_dir }}"

    - name: Remove desktop autostart file
      ansible.builtin.file:
        path: "~/.config/autostart/cockos-reaper.desktop"
        state: absent

    - name: Create systemd service file
      ansible.builtin.copy:
        dest: "/etc/systemd/user/{{ systemd_service_name }}.service"
        content: |
          [Unit]
          Description=REAPER
          After=user-network-online.service graphical-session.target jack.service dbus.service
          Wants=user-network-online.service graphical-session.target

          [Service]
          Type=simple
          ExecStart=/opt/REAPER/reaper
          Restart=on-failure

          [Install]
          WantedBy=default.target
        mode: u=rw,g=r,o=r
      become: true

    - name: Systemd daemon reload
      ansible.builtin.systemd:
        daemon_reload: true
        scope: user

    - name: Systemd enable service
      ansible.builtin.systemd:
        service: "{{ systemd_service_name }}.service"
        enabled: true
        scope: user
        masked: false

      # - name: Setup
