---
- name: Setup BTRFS Subvolumes
  hosts: all
  vars_files:
    - ../vars/vault.yml
  vars:
    subvolumes:
      - name: "@home"
        mount_point: /home
      - name: "@var/@cache"
        mount_point: /var/cache
      - name: "@var/@log"
        mount_point: /var/log
      - name: "@var"
        mount_point: /var
      - name: "@snapshots"
        mount_point: /.snapshots
    mount_options: defaults,noatime,nodiratime,ssd,compress=zstd:3,subvol=
  tasks:
    - name: Check existence of @rootfs subvolume
      community.general.btrfs_subvolume:
        name: "@rootfs"
        filesystem_label: system
      become: true
      register: fs_info

    - name: Create subvolumes
      community.general.btrfs_subvolume:
        name: "{{ item.name }}"
        filesystem_label: system
        automount: true
        recursive: true
      become: true
      loop: "{{ subvolumes }}"

    - name: Unmount Subvolume
      ansible.posix.mount:
        fstype: btrfs
        path: /mnt{{ item.mount_point }}
        src: UUID={{ fs_info.filesystem.uuid }}
        state: unmounted
      loop: "{{ subvolumes }}"
      ignore_errors: true
      throttle: 1
      # only do this when the subvolume isn't mounted where it should go
      when: ansible_mounts | selectattr('mount', 'equalto', item.mount_point) | list | length == 0
      become: true

    - name: Unmount Subvolume a second time for reasons
      ansible.posix.mount:
        fstype: btrfs
        path: /mnt{{ item.mount_point }}
        src: UUID={{ fs_info.filesystem.uuid }}
        state: unmounted
      loop: "{{ subvolumes }}"
      throttle: 1
      # only do this when the subvolume isn't mounted where it should go
      when: ansible_mounts | selectattr('mount', 'equalto', item.mount_point) | list | length == 0
      become: true

    - name: Mount Subvolume temporarily
      ansible.posix.mount:
        fstype: btrfs
        path: /mnt{{ item.mount_point }}
        src: UUID={{ fs_info.filesystem.uuid }}
        state: ephemeral
        opts: "{{ mount_options }}{{ item.name }}"
      loop: "{{ subvolumes }}"
      throttle: 1
      # only do this when the subvolume isn't mounted where it should go
      when: ansible_mounts | selectattr('mount', 'equalto', item.mount_point) | list | length == 0
      become: true
    - name: check if original directory exists
      ansible.builtin.stat:
        path: "{{ item.mount_point }}"
      loop: "{{ subvolumes }}"
      register: origin_dir
    - name: debug
      ansible.builtin.debug:
        var: origin_dir
    # this might lead to problems with ssh keys
    - name: Move data
      ansible.builtin.shell:
        cmd: "mv {{ item.mount_point }}/* /mnt{{ item.mount_point }}/; mv {{ item.mount_point }} {{ item.mount_point }}.old"
      become: true
      loop: "{{ subvolumes }}"
      when: origin_dir.results[index].stat.exists == true and (ansible_mounts | selectattr('mount', 'equalto', item.mount_point) | list | length == 0) 
      loop_control:
        index_var: index
      throttle: 1

    - name: Mount Subvolume permanently
      ansible.posix.mount:
        fstype: btrfs
        path: "{{ item.mount_point }}"
        src: UUID={{ fs_info.filesystem.uuid }}
        state: mounted
        opts: "{{ mount_options }}{{ item.name }}" 
      loop: "{{ subvolumes }}"
      become: true
      
    - name: Delete old directory
      ansible.builtin.file:
        path: "{{ item.mount_point }}.old"
        state: absent
      loop: "{{ subvolumes }}"
      # only do this when the subvolume isn't mounted where it should go
      when: ansible_mounts | selectattr('mount', 'equalto', item.mount_point) | list | length == 0
      become: true
    



    - ansible.builtin.debug:
        msg: "{{  fs_info.filesystem.uuid }}"