---
- name: initial setup of harddrives
  hosts: all
  vars_files:
    - ../vars/vault.yml
  tasks:
    - name: Get UUID of main partition
      shell: lsblk -n -o UUID {{ block_device }}
      register: root_out
      vars:
        block_device: /dev/nvme0n1p2
    - name: Get UUID of home partiiton
      shell: lsblk -n -o UUID {{ block_device }}
      register: home_out
      vars:
        block_device: /dev/nvme0n1p3

    - name: Setup fstab for root partition
      ansible.posix.mount:
        fstype: btrfs
        path: /
        src: UUID={{ root_out.stdout }}
        state: mounted
        backup: true
        opts: defaults,noatime,nodiratime,ssd,compress=zstd:3,subvol=@rootfs
      become: true

    - name: Setup fstab for home partition
      ansible.posix.mount:
        fstype: btrfs
        path: /home
        src: UUID={{ home_out.stdout }}
        state: mounted
        backup: true
        opts: defaults,noatime,nodiratime,ssd,compress=zstd:3
      become: true

    # - name: Set mount option for SSDs with btrfs
    #   ansible.builtin.lineinfile:
    #     path: /etc/fstab
    #     regexp: "^UUID={{ lsblk_out.stdout }}"
    #     line: "UUID={{ lsblk_out.stdout }} /               btrfs   defaults,noatime,nodiratime,ssd,compress=zstd:3,subvol=@rootfs 0       0"
    #   become: true
    #   register: fstab_changed
    # - name: Reboot if necessary
    #   ansible.builtin.reboot:
    #   when: fstab_changed.changed